bonemeal:add_sapling({
	{"australia:black_box_sapling", australia.grow_black_box_sapling, "soil"},
	{"australia:black_wattle_sapling", australia.grow_black_wattle_sapling, "soil"},
	{"australia:blue_gum_sapling", australia.grow_blue_gum_sapling, "soil"},
	{"australia:boab_sapling", australia.grow_boab_sapling, "soil"},
	{"australia:bull_banksia_sapling", australia.grow_bull_banksia_sapling, "soil"},
	{"australia:celery_top_pine_sapling", australia.grow_celery_top_pine_sapling, "soil"},
	{"australia:cherry_sapling", australia.grow_cherry_sapling, "soil"},
	{"australia:cloncurry_box_sapling", australia.grow_cloncurry_box_sapling, "soil"},
	{"australia:coast_banksia_sapling", australia.grow_coast_banksia_sapling, "soil"},
	{"australia:coast_banksia_small_sapling", australia.grow_coast_banksia_small_sapling, "soil"},
	{"australia:coolabah_sapling", australia.grow_coolabah_sapling, "soil"},
	{"australia:daintree_stringybark_sapling", australia.grow_daintree_stringybark_sapling, "soil"},
	{"australia:darwin_woollybutt_sapling", australia.grow_darwin_woollybutt_sapling, "soil"},
	{"australia:desert_oak_sapling", australia.grow_desert_oak_sapling, "soil"},
	{"australia:fan_palm_sapling", australia.grow_fan_palm_sapling, "soil"},
	{"australia:golden_wattle_sapling", australia.grow_golden_wattle_sapling, "soil"},
	{"australia:grey_mangrove_sapling", australia.grow_grey_mangrove_sapling, "soil"},
	{"australia:huon_pine_sapling", australia.grow_huon_pine_sapling, "soil"},
	{"australia:illawarra_flame_sapling", australia.grow_illawarra_flame_sapling, "soil"},
	{"australia:jarrah_sapling", australia.grow_jarrah_sapling, "soil"},
	{"australia:karri_sapling", australia.grow_karri_sapling, "soil"},
	{"australia:lemon_eucalyptus_sapling", australia.grow_lemon_eucalyptus_sapling, "soil"},
	{"australia:lemon_myrtle_sapling", australia.grow_lemon_myrtle_sapling, "soil"},
	{"australia:lilly_pilly_sapling", australia.grow_lilly_pilly_sapling, "soil"},
	{"australia:macadamia_sapling", australia.grow_macadamia_sapling, "soil"},
	{"australia:mangrove_apple_sapling", australia.grow_mangrove_apple_sapling, "soil"},
	{"australia:marri_sapling", australia.grow_marri_sapling, "soil"},
	{"australia:merbau_sapling", australia.grow_merbau_sapling, "soil"},
	{"australia:moreton_bay_fig_sapling", australia.grow_moreton_bay_fig_sapling, "soil"},
	{"australia:mulga_sapling", australia.grow_mulga_sapling, "soil"},
	{"australia:paperbark_sapling", australia.grow_paperbark_sapling, "soil"},
	{"australia:quandong_sapling", australia.grow_quandong_sapling, "soil"},
	{"australia:red_bottlebrush_sapling", australia.grow_red_bottlebrush_sapling, "soil"},
	{"australia:river_oak_sapling", australia.grow_river_oak_sapling, "soil"},
	{"australia:river_oak_small_sapling", australia.grow_river_oak_small_sapling, "soil"},
	{"australia:river_red_gum_sapling", australia.grow_river_red_gum_sapling, "soil"},
	{"australia:rottnest_island_pine_sapling", australia.grow_rottnest_island_pine_sapling, "soil"},
	{"australia:scribbly_gum_sapling", australia.grow_scribbly_gum_sapling, "soil"},
	{"australia:shoestring_acacia_sapling", australia.grow_shoestring_acacia_sapling, "soil"},
	{"australia:snow_gum_sapling", australia.grow_snow_gum_sapling, "soil"},
	{"australia:southern_sassafras_sapling", australia.grow_southern_sassafras_sapling, "soil"},
	{"australia:stilted_mangrove_sapling", australia.grow_stilted_mangrove_sapling, "soil"},
	{"australia:sugar_gum_sapling", australia.grow_sugar_gum_sapling, "soil"},
	{"australia:swamp_bloodwood_sapling", australia.grow_swamp_bloodwood_sapling, "soil"},
	{"australia:swamp_gum_sapling", australia.grow_swamp_gum_sapling, "soil"},
	{"australia:swamp_paperbark_sapling", australia.grow_swamp_paperbark_sapling, "soil"},
	{"australia:tasmanian_myrtle_sapling", australia.grow_tasmanian_myrtle_sapling, "soil"},
	{"australia:tea_tree_sapling", australia.grow_tea_tree_sapling, "soil"},
	{"australia:white_box_sapling", australia.grow_white_box_sapling, "soil"},
	{"australia:wirewood_sapling", australia.grow_wirewood_sapling, "soil"}
})

bonemeal:add_deco({
	{"australia:mangrove_mud", {}, {"australia:mangrove_fern", "australia:mangrove_lily", "", ""}},
	{"australia:red_gravel", {"default:dry_grass_1", "default:dry_grass_2", "", ""}, {"australia:mitchell_grass", "australia:spinifex"}},
	{"australia:red_dirt", {"default:dry_grass_1", "default:dry_grass_2", "default:dry_grass_3", "", ""}, {"australia:mitchell_grass", "australia:spinifex"}},
	-- {"default:sand", {"australia:sea_grass"}, {}},
	-- {"default:dirt_with_grass", {"australia:fern", "australia:small_fern", "australia:moss", "australia:moss_with_fungus"}, {"australia:couch_honeypot", "australia:mangrove_fern", "australia:mangrove_lily"}},
	-- {"default:dirt_with_dry_grass", {}, {"australia:mitchell_grass", "australia:darling_lily", "australia:saltbush", "australia:silver_daisy", "", ""}},
	-- {"default:dirt", {}, {"australia:mangrove_fern", "australia:mangrove_lily"}}
})